/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package component;

import java.util.Set;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import dao.ChiTietVeDao;
import dao.HoaDonDao;
import dao.KhachHangDao;
import dao.VeDao;
import entity.ChiTietVe;
import entity.Ga;
import entity.HoaDon;
import entity.KhuyenMai;
import entity.Ve;
import jakarta.persistence.EntityManagerFactory;

public class jFrameMuaVe extends javax.swing.JFrame {

	private HoaDon hoadon;
	private HoaDonDao hoaDonDao;
	private KhachHangDao khachHangDao;
	private VeDao veDao;
	private ChiTietVeDao chiTietVeDao;
	private EntityManagerFactory emf;
	private boolean isAddHoaDon;
	
    public jFrameMuaVe(EntityManagerFactory emf, HoaDon hd) {
    	this.hoadon = hd;
    	this.emf = emf;
    	this.khachHangDao = new KhachHangDao(emf);
    	this.veDao = new VeDao(emf);
    	this.chiTietVeDao = new ChiTietVeDao(emf);
    	this.hoaDonDao = new HoaDonDao(emf);
    	this.isAddHoaDon = false;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        addLable();
    }
    
    
    
    
    public boolean isAddHoaDon() {
		return isAddHoaDon;
	}




	public void setAddHoaDon(boolean isAddHoaDon) {
		this.isAddHoaDon = isAddHoaDon;
	}




	public HoaDon getHoadon() {
		return hoadon;
	}



	public void setHoadon(HoaDon hoadon) {
		this.isAddHoaDon = false;
		this.hoadon = hoadon;
	}



	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCCCD = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        lbSdt = new javax.swing.JLabel();
        lbSLV = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jtGia = new javax.swing.JTextField();
        btnTreoD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        ifCccd = new javax.swing.JLabel();
        ifHoTen = new javax.swing.JLabel();
        ifSdt = new javax.swing.JLabel();
        ifSLV = new javax.swing.JLabel();
        ifTongT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ifTienThoi = new javax.swing.JLabel();
        ifKhuyenMai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbCCCD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbCCCD.setText("CCCD:");

        lbHoTen.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbHoTen.setText("Họ tên:");

        lbSdt.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbSdt.setText("Số điện thoại:");

        lbSLV.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbSLV.setText("Số lượng vé:");

        lbTongTien.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbTongTien.setText("Tổng tiền:");

        jtGia.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jtGia.setPreferredSize(new java.awt.Dimension(91, 40));
        jtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtGiaKeyReleased(evt);
            }
        });

        btnTreoD.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnTreoD.setText("Treo đơn");
        btnTreoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreoDMouseClicked(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 51, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Xác nhận thông tin mua vé");

        ifCccd.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifCccd.setText(" ");

        ifHoTen.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifHoTen.setText(" ");

        ifSdt.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifSdt.setText(" ");

        ifSLV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ifSLV.setText(" ");

        ifTongT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ifTongT.setText(" ");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setText("Khuyến mãi:");

        ifTienThoi.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifTienThoi.setText(" ");

        ifKhuyenMai.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ifKhuyenMai.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCCCD)
                        .addContainerGap(409, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTreoD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ifTienThoi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHoTen)
                                    .addComponent(lbSdt)
                                    .addComponent(lbSLV)
                                    .addComponent(lbTongTien)
                                    .addComponent(jLabel1))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ifKhuyenMai)
                                    .addComponent(ifTongT)
                                    .addComponent(ifSLV)
                                    .addComponent(ifSdt)
                                    .addComponent(ifCccd)
                                    .addComponent(ifHoTen))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(title)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCCCD)
                    .addComponent(ifCccd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoTen)
                    .addComponent(ifHoTen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSdt)
                    .addComponent(ifSdt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSLV)
                    .addComponent(ifSLV))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTien)
                    .addComponent(ifTongT))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ifKhuyenMai))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifTienThoi))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTreoD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGiaKeyReleased
    	try {
    		double tienNhap = Double.parseDouble(jtGia.getText());
    		double tongTien = Double.parseDouble(ifTongT.getText().substring(0, ifTongT.getText().length()-4));
    		if(tienNhap - tongTien >= 1000) {
    			ifTienThoi.setText((tienNhap-tongTien)+"");
    		}
    		else {
				ifTienThoi.setText(" ");
			}
    	}
    	catch (Exception e) {
			JOptionPane.showConfirmDialog(null, "Chỉ được nhập số", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_jtGiaKeyReleased

    private void btnTreoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreoDMouseClicked
    	String tien = jtGia.getText();
    	if(tien.equals(""))
    		JOptionPane.showConfirmDialog(null, "Chưa nhập số tiền thanh toán", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    	try {
    		double tienNhap = Double.parseDouble(tien);
    		double tongTien = Double.parseDouble(ifTongT.getText().substring(0, ifTongT.getText().length()-4));
    		if(tienNhap - tongTien >= 0) {
    			if(khachHangDao.getKhachHangByCCCD(hoadon.getKhachHang().getCccd()) == null)
    				khachHangDao.addKhachHang(hoadon.getKhachHang());
    			hoaDonDao.addHoaDon(hoadon);
    			for(Ve v: hoadon.getListVes()) {
    				if(khachHangDao.getKhachHangByCCCD(v.getKhachHang().getCccd()) == null)
    					khachHangDao.addKhachHang(v.getKhachHang());
    				else
    					khachHangDao.updateKhachHang(v.getKhachHang());
    				veDao.addVe(v);
    				for(ChiTietVe ctv : v.getLisChiTietVes()) {
    					chiTietVeDao.addChiTietVe(ctv);
    				}
    			}
    			this.isAddHoaDon = true;
    			setVisible(false);
    		}
    		else {
    			JOptionPane.showConfirmDialog(null, "Chưa đủ số tiền", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    		}
		} catch (Exception e) {
			JOptionPane.showConfirmDialog(null, "Ô nhập tiền thanh toán không đưuọc nhập dữu liệu gì ngoài số", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnTreoDMouseClicked

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
    	String tien = jtGia.getText();
    	if(tien.equals(""))
    		JOptionPane.showConfirmDialog(null, "Chưa nhập số tiền thanh toán", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    	try {
    		double tienNhap = Double.parseDouble(tien);
    		double tongTien = Double.parseDouble(ifTongT.getText().substring(0, ifTongT.getText().length()-4));
    		if(tienNhap - tongTien >= 0) {
    			if(khachHangDao.getKhachHangByCCCD(hoadon.getKhachHang().getCccd()) == null)
    				khachHangDao.addKhachHang(hoadon.getKhachHang());
    			hoaDonDao.addHoaDon(hoadon);
    			for(Ve v: hoadon.getListVes()) {
    				if(khachHangDao.getKhachHangByCCCD(v.getKhachHang().getCccd()) == null)
    					khachHangDao.addKhachHang(v.getKhachHang());
    				else
    					khachHangDao.updateKhachHang(v.getKhachHang());
    				veDao.addVe(v);
    				for(ChiTietVe ctv : v.getLisChiTietVes()) {
    					chiTietVeDao.addChiTietVe(ctv);
    				}
    			}
    			this.isAddHoaDon = true;
    			setVisible(false);
    		}
    		else {
    			JOptionPane.showConfirmDialog(null, "Chưa đủ số tiền", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    		}
		} catch (Exception e) {
			JOptionPane.showConfirmDialog(null, "Ô nhập tiền thanh toán không đưuọc nhập dữu liệu gì ngoài số", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
			e.printStackTrace();
		}
    	
    }//GEN-LAST:event_btnThanhToanMouseClicked

   
    private void addLable() {
    	ifCccd.setText(hoadon.getKhachHang().getCccd());
    	ifHoTen.setText(hoadon.getKhachHang().getHoTen());
    	ifSdt.setText(hoadon.getKhachHang().getSdt());
    	ifSLV.setText(hoadon.getListVes().size()+"");
    	
    	double tongTien = 0;
    	for(Ve ve : hoadon.getListVes()) {
    		Ga gaDi = null;
    		Ga gaDen = null;
    		for(ChiTietVe ctv : ve.getLisChiTietVes()) {
    			if(ctv.isChieu()) {
    				gaDi = ctv.getGa();
    			}
    			else {
    				gaDen = ctv.getGa();
    			}
    		}
    		tongTien += ve.getChoNgoi().getGia()*Math.abs(gaDi.getId()-gaDen.getId())*(ve.getKhuyenMai() == null ? 1 : 1-ve.getKhuyenMai().getChietKhau());
    	}
    	if(hoadon.getLisKhuyenMais() != null) {
    		String temp = "";
    		int count = 0;
    		for(KhuyenMai km : hoadon.getLisKhuyenMais()) {
    			temp += km.getTenKhuyenMai();
    			tongTien *= km.getChietKhau();
    			if(count > 1)
    				temp += ", ";
    			count++;
    		}
    		ifKhuyenMai.setText(temp);
    	}
    	
    	ifTongT.setText((int)tongTien+" VND");
    	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTreoD;
    private javax.swing.JLabel ifCccd;
    private javax.swing.JLabel ifHoTen;
    private javax.swing.JLabel ifKhuyenMai;
    private javax.swing.JLabel ifSLV;
    private javax.swing.JLabel ifSdt;
    private javax.swing.JLabel ifTienThoi;
    private javax.swing.JLabel ifTongT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtGia;
    private javax.swing.JLabel lbCCCD;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbSLV;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
